In [1]:
!pip install numpy

In [2]:
import numpy as np
import time

In [5]:
arr = np.array([[1,2,3],[44,5,6]])
print(arr.ndim) # for check dimensions
print(arr.dtype) # for check array type like int, float etc
print(arr.shape) # for check rows and column

2
int64
(2, 3)


In [21]:
# check execution time of python list 
py_list = list(range(1000000))
arr=[]
start_time = time.time()
for i in py_list:
    arr.append(i+5)
end_time = time.time()
print(f"Python list execute time is: {end_time - start_time}")

Python list execute time is: 0.31888484954833984


In [22]:
# check execution time of numpy array
np_array = np.array(1000000)
start_time = time.time()
np_result = np_array+5
end_time = time.time()
print(f"Numpy array execute time is: {end_time - start_time}")

Numpy array execute time is: 0.00025081634521484375


In [23]:
# create array in numpy 
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [25]:
print(np.zeros((2,3))) # for create initialize array as zero

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
print(np.ones((2,3))) # for create initialize array as one

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
print(np.full((2,3),7)) # for create initialize array as custom values

[[7 7 7]
 [7 7 7]]


In [29]:
print(np.arange(0,10,2)) # for create initialize array as which start 0 and end 10 with setp 2

[0 2 4 6 8]


In [31]:
print(np.linspace(0,1,5)) # for create initialize array as, start 0 and end 1 with 5 step and divide 5 equal parts

[0.   0.25 0.5  0.75 1.  ]


In [32]:
print(np.eye(3)) # for create identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
print(np.diag([1,2,3])) # for create diagnal value

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [34]:
np.array([1,2,3],dtype=float) # for change data type

array([1., 2., 3.])

In [35]:
arr = np.array([1.5,2.7,3.9])
print(arr.astype(int))

[1 2 3]
