In [1]:
!pip install numpy

In [6]:
import numpy as np
import time

In [5]:
arr = np.array([[1,2,3],[44,5,6]])
print(arr.ndim) # for check dimensions
print(arr.dtype) # for check array type like int, float etc
print(arr.shape) # for check rows and column

2
int64
(2, 3)


In [21]:
# check execution time of python list 
py_list = list(range(1000000))
arr=[]
start_time = time.time()
for i in py_list:
    arr.append(i+5)
end_time = time.time()
print(f"Python list execute time is: {end_time - start_time}")

Python list execute time is: 0.31888484954833984


In [22]:
# check execution time of numpy array
np_array = np.array(1000000)
start_time = time.time()
np_result = np_array+5
end_time = time.time()
print(f"Numpy array execute time is: {end_time - start_time}")

Numpy array execute time is: 0.00025081634521484375


In [23]:
# create array in numpy 
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [25]:
print(np.zeros((2,3))) # for create initialize array as zero

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
print(np.ones((2,3))) # for create initialize array as one

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
print(np.full((2,3),7)) # for create initialize array as custom values

[[7 7 7]
 [7 7 7]]


In [29]:
print(np.arange(0,10,2)) # for create initialize array as which start 0 and end 10 with setp 2

[0 2 4 6 8]


In [31]:
print(np.linspace(0,1,5)) # for create initialize array as, start 0 and end 1 with 5 step and divide 5 equal parts

[0.   0.25 0.5  0.75 1.  ]


In [32]:
print(np.eye(3)) # for create identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
print(np.diag([1,2,3])) # for create diagnal value

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [8]:
np.array([1,2,3],dtype=float) # for change data type

array([1., 2., 3.])

In [9]:
arr = np.array([1.5,2.7,3.9])
print(arr.astype(int))

[1 2 3]


In [11]:
or_arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [13]:
print(or_arr[0,1]) # row 0, col 1
print(or_arr[2,2]) # row 2 col 2
print(or_arr[-3,-3]) # row 1 col 1

20
90
10


In [15]:
# general form : or_arr[start:stop:step]
print(or_arr[0:2,1:3]) # rows 0-1, cols 1-2

[[20 30]
 [50 60]]


In [17]:
print(or_arr[::2,::2]) # every 2nd row and 2nd column

[[10 30]
 [70 90]]


In [20]:
slice_arr=or_arr[0,:2] # view not a copy
slice_arr[0]=999

In [21]:
print(slice_arr[0]) # original changes

999


In [22]:
copy_arr= or_arr[1].copy() # independent copy
copy_arr[0]=555

In [26]:
print(or_arr[1]) # original unchanged
print(copy_arr[1])

[40 50 60]
50


In [35]:
# simulate 100k coin flips
rng = np.random.default_rng(seed=43) # seed use for same random number sequence generator witout seed some times head increase and some time tial increase
flips = rng.integers(0,2,size=100000) # 0-tail, 1=heads
prob_heads = np.mean(flips)
print("Estimated probability of heads: ", prob_heads)

Estimated probability of heads:  0.50238


In [44]:
# vectorization 
# python loop 
start = time.time()
squares = [i**2 for i in range (1000000)]
end = time.time()
print("Loop time: ", end-start)

# numpy vectrized 
start = time.time()
arr = np.arange(1000000)
squares_np = arr**2
end= time.time()
print("Vectrized time: ", end-start)

Loop time:  0.018044471740722656
Cectrized time:  53.746931314468384
